Экран со списком эпизодов - вёрстка
sscracker/RickAndMortyApi pull request #10
Opened 2023-10-19 10:45 UTC by sscracker

https://trello.com/c/Zcagu5O6

2023-10-19 13:57 UTC, elza-khamdeeva requested changes

2023-10-19 13:57 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/episodes/list/adapter/EpisodesListAdapter.kt
> +        holder.airDate.text = "Episode Airdate"
почему в коде, а не в верстке?

2023-10-19 13:57 UTC, elza-khamdeeva commented on app/src/main/res/drawable/icon_episode.png
переведи в webP

2023-10-19 13:57 UTC, elza-khamdeeva commented on app/src/main/res/drawable/icon_rick.png
переведи в webP

2023-10-19 13:57 UTC, elza-khamdeeva commented on app/src/main/res/layout/fragment_episodes.xml
> +
лишний перенос

2023-10-19 14:01 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/episodes/list/adapter/EpisodesListAdapter.kt
> +        holder.airDate.text = "Episode Airdate"
Я назначил пока дефолтные значения, потом тут будут стоять данные приходящие с бэка

2023-10-20 11:05 UTC, sscracker commented on app/src/main/res/drawable/icon_episode.png
готово

2023-10-20 11:05 UTC, sscracker commented on app/src/main/res/drawable/icon_rick.png
готово

2023-10-20 11:05 UTC, sscracker commented on app/src/main/res/layout/fragment_episodes.xml
> +
готово

2023-10-20 15:13 UTC, elza-khamdeeva approved these changes

2023-10-21 08:41 UTC, merged