Feature/rm5
sscracker/RickAndMortyApi pull request #2
Opened 2023-09-11 13:09 UTC by sscracker

Создание разметки для экрана с персонажами. Создание списка с персонажами, фрагмента и активити, отвечающих за этот экран

2023-09-11 13:55 UTC, elza-khamdeeva requested changes

2023-09-11 13:55 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/MainActivity.kt
> +            replace(R.id.fragment_container,charactersListFragment, CharactersListFragment.CHARACTERS_TAG)
не хватает пробела перед charactersListFragment
не забывай форматировать код горячими клавишами

2023-09-11 13:55 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/CharacterListDetailsListener.kt
> +
лишние переносы строк нужно убрать

2023-09-11 13:55 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/CharactersListFragment.kt
> +
лишний перенос строки

2023-09-11 13:55 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/CharactersListFragment.kt
> +
лишний перенос строки

2023-09-11 13:55 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/CharactersListFragment.kt
> +        fun newInstance() = CharactersListFragment()
давай companion object перенесем в конец файла

2023-09-11 13:55 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/CharactersListFragment.kt
> +    private val binding get() = _binding!!
нужно отформатировать код, пройдись по всем файлам

2023-09-11 13:55 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/CharactersListFragment.kt
> + private lateinit var characterAdapter: CharactersListAdapter
вместо lateinit лучше использовать by lazy во избежание получения исключений
либо так: private var characterAdapter: CharactersListAdapter? = null

lateinit используем только для полей, который инжектятся через DI, если это необходимо

2023-09-11 13:55 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/CharactersListFragment.kt
> +            layoutManager = GridLayoutManager(requireActivity(), 2)
2 - это magic number
давай вынесем его в константу, например
private const val COLUMN_COUNT = 2

2023-09-11 13:55 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/CharactersListFragment.kt
> +            adapter = adapter
здесь нужно быть внимательным, точно ли к тому адаптеру обращаешься
кажется, здесь должно быть adapter = characterAdapter

2023-09-11 13:55 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/SingleCharacter.kt
> +    val status: String
отформатируй код)

2023-09-11 13:55 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/adapter/CharactersListAdapter.kt
> +{
лишние комментарии нужно убрать

2023-09-11 13:55 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/adapter/CharactersListAdapter.kt
> +{
логичнее было бы назвать CharacterListAdapter или CharactersAdapter

2023-09-11 13:55 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/adapter/CharactersListAdapter.kt
> +    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): CharactersListViewHolder {
добавь перенос строки

2023-09-11 13:55 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/adapter/CharactersListAdapter.kt
> +
а здесь убери лишние переносы строк

2023-09-11 13:55 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/adapter/CharactersListAdapter.kt
> +
можно так
override fun getItemCount() = charactersList.size

2023-09-11 13:55 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/adapter/CharactersListAdapter.kt
> +    private val charactersList = mutableListOf<SingleCharacter>()
здесь аналогично с названием класса

2023-09-11 13:55 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/adapter/CharactersListAdapter.kt
> +
лишний перенос строки

2023-09-11 13:55 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/adapter/CharactersListViewHolder.kt
> +    /*private val characterListDetailsListener: CharacterListDetailsListener*/
давай уберем лишний комментарий
потом добавишь это поле в следующих задачах, когда будет нужно

2023-09-11 13:55 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/adapter/CharactersListViewHolder.kt
> +
лишний перенос строки, посмотри по всему файлу

2023-09-11 13:55 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/adapter/CharactersListViewHolder.kt
> +        }*/
давай уберем пока нам ненужный код

2023-09-11 13:55 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/adapter/CharactersListViewHolder.kt
> +    }
отформатируй код)

2023-09-11 13:55 UTC, elza-khamdeeva commented on app/src/main/res/drawable/rick.jpg
можно сконвертировать файл в webP 
для сокращения размера

попробуй прямо в студии в контекстном меню у файла найти convert to webP

2023-09-11 13:55 UTC, elza-khamdeeva commented on app/src/main/res/layout/fragment_characters.xml
> +
лишние переносы строк

2023-09-11 13:55 UTC, elza-khamdeeva commented on app/src/main/res/layout/fragment_characters.xml
> +            android:id="@+id/characters_rv"
давай будем давать более читабельные названия?
например, recycler_view_characters

и сделаем названия всех view в едином стиле

2023-09-11 13:55 UTC, elza-khamdeeva commented on app/src/main/res/layout/fragment_characters.xml
> +
лишние переносы

2023-09-11 13:55 UTC, elza-khamdeeva commented on app/src/main/res/layout/fragment_characters.xml
сейчас кажется, что можно было бы обойтись FrameLayout
если файл верстки останется в будущем такой же простой, то лучше переделать

если предполагается более сложная верстка, то можно оставить ConstraintLayout

2023-09-11 13:55 UTC, elza-khamdeeva commented on app/src/main/res/layout/item_character.xml
> +        android:id="@+id/character_name"
text_view_character

так, в коде будет сразу понятно, что это вью из верстки, а не просто переменная
с остальными вью аналогично

2023-09-11 13:55 UTC, elza-khamdeeva commented on app/src/main/res/values/themes.xml
>      </style>
здесь можно убрать закрывающий тег, пока внутри нет других элементов

<style name="Base.Theme.RickAndMortyProject" parent="Theme.MaterialComponents.DayNight.DarkActionBar" />

2023-09-11 13:55 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/CharacterListDetailsListener.kt
> +    fun charactersListener(character: SingleCharacter)
метод нужно переименовать, сейчас из названия непонятно его назначение
fun onCharacterClick(character: SingleCharacter)

2023-09-12 16:12 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/MainActivity.kt
> +            replace(R.id.fragment_container,charactersListFragment, CharactersListFragment.CHARACTERS_TAG)
готово

2023-09-12 16:13 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/CharacterListDetailsListener.kt
> +
готово

2023-09-12 16:13 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/CharactersListFragment.kt
> +
готово

2023-09-12 16:14 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/CharactersListFragment.kt
> +
готово

2023-09-12 16:15 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/CharactersListFragment.kt
> +        fun newInstance() = CharactersListFragment()
готово

2023-09-12 16:16 UTC, sscracker commented on app/src/main/res/layout/fragment_characters.xml
> +
готово

2023-09-12 16:17 UTC, sscracker commented on app/src/main/res/layout/fragment_characters.xml
нет, вёрстка, этого фрагмента, скорее всего, останется такой же

2023-09-12 16:20 UTC, sscracker commented on app/src/main/res/layout/fragment_characters.xml
добавлю вероятно всего toolbar, searchview и оберну список в swiperefreshlayout

2023-09-12 16:22 UTC, sscracker commented on app/src/main/res/layout/item_character.xml
> +        android:id="@+id/character_name"
готово

2023-09-12 16:22 UTC, sscracker commented on app/src/main/res/values/themes.xml
>      </style>
готово

2023-09-12 16:23 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/CharacterListDetailsListener.kt
> +    fun charactersListener(character: SingleCharacter)
готово

2023-09-13 11:36 UTC, sscracker commented on app/src/main/res/layout/fragment_characters.xml
> +            android:id="@+id/characters_rv"
готово

2023-09-13 11:36 UTC, sscracker commented on app/src/main/res/layout/fragment_characters.xml
> +
готово

2023-09-13 11:36 UTC, sscracker commented on app/src/main/res/drawable/rick.jpg
готово

2023-09-13 11:36 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/adapter/CharactersListViewHolder.kt
> +    }
готово

2023-09-13 11:36 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/adapter/CharactersListViewHolder.kt
> +        }*/
готово

2023-09-13 11:36 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/adapter/CharactersListViewHolder.kt
> +
готово

2023-09-13 11:36 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/adapter/CharactersListViewHolder.kt
> +    /*private val characterListDetailsListener: CharacterListDetailsListener*/
готово

2023-09-13 11:37 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/adapter/CharactersListAdapter.kt
> +
готово

2023-09-13 11:38 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/adapter/CharactersListAdapter.kt
> +    private val charactersList = mutableListOf<SingleCharacter>()
готово

2023-09-13 11:39 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/adapter/CharactersListAdapter.kt
> +
готово

2023-09-13 11:39 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/adapter/CharactersListAdapter.kt
> +    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): CharactersListViewHolder {
готово

2023-09-13 11:39 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/adapter/CharactersListAdapter.kt
> +{
готово

2023-09-13 11:39 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/SingleCharacter.kt
> +    val status: String
готово

2023-09-13 11:39 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/CharactersListFragment.kt
> +            adapter = adapter
готово

2023-09-13 11:39 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/CharactersListFragment.kt
> +            layoutManager = GridLayoutManager(requireActivity(), 2)
готово

2023-09-13 11:40 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/CharactersListFragment.kt
> + private lateinit var characterAdapter: CharactersListAdapter
я сделаю пока через null, а потом когда повешу слушатель, то сделаю через lazy тогда

2023-09-13 11:41 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/CharactersListFragment.kt
> +    private val binding get() = _binding!!
готово

2023-09-13 14:07 UTC, elza-khamdeeva requested changes

2023-09-13 14:07 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/CharactersListFragment.kt
> +private const val COLUMN_COUNT = 2
добавь перенос строки после импорта
и после const

а то все сливается)

2023-09-13 14:08 UTC, elza-khamdeeva requested changes

2023-09-13 14:08 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/adapter/CharacterListAdapter.kt
> +
лишний перенос строки

2023-09-13 14:08 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/adapter/CharacterListViewHolder.kt
> +
лишний перенос строки

2023-09-13 14:26 UTC, elza-khamdeeva approved these changes

2023-09-13 15:09 UTC, merged