Экран со списком эпизодов - детали эпизодов
sscracker/RickAndMortyApi pull request #20
Opened 2023-11-07 12:39 UTC by sscracker

https://trello.com/c/LQP8SHJh

2023-11-07 15:17 UTC, elza-khamdeeva requested changes

2023-11-07 15:17 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/episodes/details/EpisodeDetailsFragment.kt
> +    private var episode: EpisodeEntity? = null
loadedCount и episode лучше хравнить во вьюмодели
убираем всю логику туда, во фрагменте только отображение

2023-11-07 15:17 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/episodes/details/EpisodesDetailsViewModel.kt
> +    fun onViewCreated(id: Int) {
можем убрать метод, а логику перенести в блок init {} ?

2023-11-08 05:18 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/episodes/details/EpisodeDetailsFragment.kt
> +    private var episode: EpisodeEntity? = null
готово

2023-11-08 05:53 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/episodes/details/EpisodesDetailsViewModel.kt
> +    fun onViewCreated(id: Int) {
нет, тут через init не получится

2023-11-08 08:24 UTC, elza-khamdeeva requested changes

2023-11-08 08:24 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/episodes/details/EpisodeDetailsFragment.kt
> +        viewModel.episode = episodeEntity
почему сохраняем эпизод не во вьюмодели?

2023-11-08 08:30 UTC, elza-khamdeeva requested changes

2023-11-08 08:30 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/episodes/details/EpisodeDetailsFragment.kt
> +        viewModel.onViewCreated(episodeId)
давай episodeId прокидывать в конструктор вьюмодели через assisted inject, отсюда его уберем
тогда можно будет избавиться от viewModel.onViewCreated и перенести логику в блок init

2023-11-08 08:30 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/episodes/details/EpisodeDetailsFragment.kt
> +    private fun subscribeEpisodeDetailsFlow() {
по-моему нужно переименовать метод
внутри метода подписываемся на разные флоу
можно назвать метод observeData

2023-11-08 08:30 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/episodes/details/EpisodeDetailsFragment.kt
> +    private fun loadEpisode(episodeEntity: EpisodeEntity) {
неудачно назван метод
load подразумевает загрузку из какого-либо источника данных
а в методе у тебя происходит отображение данных на экране

2023-11-08 08:30 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/episodes/details/EpisodeDetailsFragment.kt
> +    private fun loadCharacters(characters: List<CharacterEntity>) {
аналогично комментарию выше

2023-11-08 08:30 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/episodes/details/EpisodeDetailsFragment.kt
> +        binding.episodeDetailsCharactersLabel.isVisible = false
почему-бы не сделать в верстке Group и скрывать/показывать элементы одной строчкой?
давай попробуем

2023-11-08 08:30 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/episodes/details/EpisodeDetailsFragment.kt
> +    }
почему-бы не сделать в верстке Group и скрывать/показывать элементы одной строчкой?
давай попробуем

2023-11-08 08:30 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/episodes/details/EpisodeDetailsFragment.kt
> +            stopProgress()
вот эту всю логику нужно спрятать во вьюмодель, а не только переменную
во вьюмодели проверять count
и при необходимости останавливаться прогресс

2023-11-08 08:47 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/episodes/details/EpisodeDetailsFragment.kt
> +    private fun loadEpisode(episodeEntity: EpisodeEntity) {
исправил

2023-11-08 08:47 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/episodes/details/EpisodeDetailsFragment.kt
> +    private fun loadCharacters(characters: List<CharacterEntity>) {
исправил

2023-11-08 08:48 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/episodes/details/EpisodeDetailsFragment.kt
> +    private fun subscribeEpisodeDetailsFlow() {
готово

2023-11-08 09:16 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/episodes/details/EpisodeDetailsFragment.kt
> +        binding.episodeDetailsCharactersLabel.isVisible = false
готово

2023-11-08 09:16 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/episodes/details/EpisodeDetailsFragment.kt
> +    }
готово

2023-11-08 09:39 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/episodes/details/EpisodeDetailsFragment.kt
> +            stopProgress()
готово

2023-11-08 10:33 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/episodes/details/EpisodeDetailsFragment.kt
> +            stopProgress()
готово

2023-11-08 13:20 UTC, elza-khamdeeva requested changes

2023-11-08 13:20 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/episodes/details/EpisodeDetailsFragment.kt
> +        if (viewModel.loading()) {
по идее вьмодель должна через флоу постить данные, когда необходимо скрыть прогресс
а фрагмент на этот флоу подписываться
не должны обращаться к вьмодели таким образом

2023-11-08 13:20 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/episodes/details/EpisodeDetailsFragment.kt
> +        if (viewModel.loading()) {
давай всю логику с показом прогресса уберем во вьюмодель

2023-11-08 13:20 UTC, elza-khamdeeva commented on app/src/main/res/layout/fragment_episode_deatils.xml
> +   </androidx.constraintlayout.widget.Group>
убери закрывающийся тэг, у тебя же внутри группы ничего не лежит

2023-11-08 15:37 UTC, elza-khamdeeva approved these changes

2023-11-08 15:52 UTC, merged