RM-24: Экран со списком локаций: детали локации
sscracker/RickAndMortyApi pull request #32
Opened 2023-11-24 14:05 UTC by sscracker

https://trello.com/c/wpNaZVGZ

2023-11-27 11:38 UTC, elza-khamdeeva requested changes

2023-11-27 11:38 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/locations/details/LocationDetailsFragment.kt
> +    private fun showContentViews() {
на мой взгляд, излишнее количество методов, хотя такой вариант тоже имеет место быть
но можно сделать попроще

    private fun showContentViews(show: Boolean) {
        binding.contentViewsGroup.isVisible = show
    }
    
 
 
   аналогично с hideErrorViews()

2023-11-27 11:38 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/locations/details/LocationDetailsFragment.kt
> +        binding.locationDetailsNameTextView.text = locationEntity.name
with(binding)

2023-11-27 11:38 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/locations/details/LocationDetailsViewModel.kt
> +    fun saveLocation(locationEntity: LocationEntity) {
давай порядок членов в классе поменяем
паблик методы над прайват

2023-11-27 11:53 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/locations/details/LocationDetailsFragment.kt
> +        binding.locationDetailsNameTextView.text = locationEntity.name
готово

2023-11-27 12:13 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/locations/details/LocationDetailsFragment.kt
> +    private fun showContentViews() {
готово

2023-11-27 12:14 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/locations/details/LocationDetailsViewModel.kt
> +    fun saveLocation(locationEntity: LocationEntity) {
готово

2023-11-28 13:17 UTC, elza-khamdeeva approved these changes

2023-11-28 13:42 UTC, merged