RM-26:  Экран со списком персонажей - детали персонажей(рефакторинг)
sscracker/RickAndMortyApi pull request #33
Opened 2023-11-29 14:43 UTC by sscracker

https://trello.com/c/2j3uTwCu

2023-11-29 17:30 UTC, elza-khamdeeva requested changes

2023-11-29 17:30 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/details/CharacterDetailsFragment.kt
> +    private fun setLocationListener() {
закинь листенеры в один метод, отдельно не нужно разносить

2023-11-29 17:30 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/details/CharacterDetailsFragment.kt
> +        if (id == -1) {
-1 надо в конст вынести

2023-11-29 17:30 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/details/CharacterDetailsFragment.kt
> +        if (id == -1) {
-1 в конст

2023-11-29 17:30 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/details/CharacterDetailsFragment.kt
> +            "%s: %s",
формат можно в конст

2023-11-29 17:30 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/details/CharacterDetailsFragment.kt
> +            "%s: %s",
тоже в конст

2023-11-29 17:30 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/details/CharacterDetailsViewModel.kt
> +        if (id == -1) {
-1 в конст

2023-11-29 17:30 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/details/CharacterDetailsViewModel.kt
> +        if (id == -1) {
-1 в конст

2023-11-29 18:09 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/details/CharacterDetailsFragment.kt
> +    private fun setLocationListener() {
готово

2023-11-29 18:10 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/details/CharacterDetailsFragment.kt
> +        if (id == -1) {
готово

2023-11-29 18:10 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/details/CharacterDetailsFragment.kt
> +        if (id == -1) {
готово

2023-11-29 18:11 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/details/CharacterDetailsFragment.kt
> +            "%s: %s",
готово

2023-11-29 18:11 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/details/CharacterDetailsFragment.kt
> +            "%s: %s",
готово

2023-11-29 18:13 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/details/CharacterDetailsViewModel.kt
> +        if (id == -1) {
готово

2023-11-29 18:13 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/details/CharacterDetailsViewModel.kt
> +        if (id == -1) {
готово

2023-11-30 11:24 UTC, elza-khamdeeva approved these changes

2023-11-30 11:24 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/details/CharacterDetailsFragment.kt
> +    private fun setOriginAndLocationListeners() {
давай просто setListeners

2023-11-30 12:05 UTC, merged