RM-27: Тестирование
sscracker/RickAndMortyApi pull request #37
Opened 2023-12-11 08:45 UTC by sscracker

https://trello.com/c/6Dqv4PEl

2023-12-13 14:05 UTC, elza-khamdeeva requested changes
предлагаю название методов тестов сделать в формате

GIVEN ... WHEN ... THEN
для того чтобы в названии методов теста не указывать название тестируемого метода, поскольку оно может поменяться

2023-12-13 14:05 UTC, elza-khamdeeva commented on app/src/test/java/ru/example/rickandmortyproject/mappers/CharactersMapperTest.kt
> +        // assertEquals("1", result.episodesId)
убираем коммент

2023-12-14 07:29 UTC, sscracker commented on app/src/test/java/ru/example/rickandmortyproject/mappers/CharactersMapperTest.kt
> +        // assertEquals("1", result.episodesId)
готово

2023-12-14 11:28 UTC, elza-khamdeeva requested changes
хорошо

но формат именования методов должен быть такой
пример:

fun /`GIVEN item_id WHEN load item THEN verify character dto/`() { }

2023-12-14 12:00 UTC, elza-khamdeeva approved these changes

2023-12-14 12:00 UTC, merged