Экран со списком персонажей - запрос + di
sscracker/RickAndMortyApi pull request #4
Opened 2023-09-19 04:04 UTC by sscracker

Реализовать запрос в сеть для списка персонажей 
Реализовать di для списка персонажей
https://trello.com/c/mHHFJPlz

2023-09-20 07:19 UTC, elza-khamdeeva requested changes

2023-09-20 07:19 UTC, elza-khamdeeva commented on app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
отдели <uses-permission от application переносом строки)

2023-09-20 07:19 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/data/characters/list/CharactersRepositoryImpl.kt
> +) : CharactersRepository {
перенос строки)

2023-09-20 07:19 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/data/characters/list/CharactersRepositoryImpl.kt
> +                try {
а сделай тоже через runCatching
пусть будет единообразно

2023-09-20 07:19 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/data/characters/list/model/SingleCharacterInfoData.kt
> +data class SingleCharacterInfoData(
мне кажется надо переименовать класс
название не отражает содержание
может быть PaginationData или CharactersPaginationData

2023-09-20 07:19 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/di/module/LocalDbModule.kt
> +            "app_db"
вынеси строку в const

2023-09-20 07:19 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/domain/characters/list/CharactersRepository.kt
> +
лишний перенос строки

2023-09-20 07:19 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/di/module/UseCaseModule.kt
> +interface UseCaseModule {
UseCaseModule и RepositoryModule можно не разделять на разные модули
сделать один CharactersBindsModule

2023-09-20 07:19 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/utils/ResponseUtil.kt
> +sealed class ResponseUtil<T : Any> {
я бы убрала из названия Util

2023-09-21 08:36 UTC, elza-khamdeeva requested changes

2023-09-21 08:36 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/di/module/BindsModule.kt
> +interface BindsModule {
я бы добавила CharactersBindsModule

когда приложение будет расширяться, могут добавиться новые разделы со своими модулями
и тогда можно будет запутаться в названиях

2023-09-21 09:38 UTC, sscracker commented on app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
готово

2023-09-21 09:38 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/data/characters/list/CharactersRepositoryImpl.kt
> +                try {
готово

2023-09-21 09:38 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/data/characters/list/CharactersRepositoryImpl.kt
> +) : CharactersRepository {
готово

2023-09-21 09:38 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/di/module/UseCaseModule.kt
> +interface UseCaseModule {
Тогда наверное просто BindsModule назвать, так как тут будут бинды не только для экрана со списком персонажей

2023-09-21 09:38 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/data/characters/list/model/SingleCharacterInfoData.kt
> +data class SingleCharacterInfoData(
Готово

2023-09-21 09:38 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/di/module/LocalDbModule.kt
> +            "app_db"
Готово

2023-09-21 09:38 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/domain/characters/list/CharactersRepository.kt
> +
Готово

2023-09-21 09:38 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/utils/ResponseUtil.kt
> +sealed class ResponseUtil<T : Any> {
Готово

2023-09-21 09:40 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/di/module/BindsModule.kt
> +interface BindsModule {
готово

2023-09-21 09:44 UTC, elza-khamdeeva approved these changes

2023-09-21 10:01 UTC, merged