Экран со списком персонажей - отображение данных
sscracker/RickAndMortyApi pull request #5
Opened 2023-09-24 23:27 UTC by sscracker

Реализация отображения данных по запросу в списке
https://trello.com/c/pGD7Pyv4

2023-09-26 13:55 UTC, elza-khamdeeva requested changes

2023-09-26 13:55 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/MainActivity.kt
>      override fun onCreate(savedInstanceState: Bundle?) {
перенос строки после переменных

2023-09-26 13:55 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/MainActivity.kt
> +        setContentView(binding?.root)
зачем тут тебе binding в активити?
setContentView(R.layout.activity_main)

2023-09-26 13:55 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/MainActivity.kt
> +    var appComponent: AppComponent = DaggerAppComponent.factory().create(this)
appComponent не должен торчать наружу
давай сделаем через интерфейс 
interface MainComponentProvider {
      fun provideMainComponent(): MainComponent
}

и я думаю, что наверное нужно сделать отдельный компонент для фичи, который будет зависеть от AppComponent через dependencies, который будет глобальный для всего проекта, его можно будет провайдить через Application класс

получится так сделать?

2023-09-26 13:55 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/di/module/CharactersViewModelModule.kt
> +        return CharacterListViewModel(
отформатируй класс

2023-09-26 13:55 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/CharacterListViewModel.kt
> +    private var characters = MutableStateFlow<ViewState<List<SingleCharacter>>>(ViewState.Loading)
перенос строки перед полем

2023-09-26 13:55 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/CharacterListViewModel.kt
> +        if (connectivity.isNetworkAvailable()){
отформатируй класс

2023-09-26 13:55 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/CharactersListFragment.kt
> +    lateinit var viewModel: CharacterListViewModel
здесь точно нужна @Inject аннотация для вьюмодели?
у тебя уже инжектится ViewModelFactory через которую ты получаешь вьюмодель

2023-09-26 13:55 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/CharactersListFragment.kt
> +        viewModel = ViewModelProvider(this, viewModelFactory)[CharacterListViewModel::class.java]
можно вынести в поле через lazy делегат?

2023-09-26 13:55 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/CharactersListFragment.kt
> +        binding.progressBar.visibility = View.GONE
binding.progressBar.isVisibile = false

2023-09-26 13:55 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/CharactersListFragment.kt
> +        binding.progressBar.visibility = View.GONE
binding.progressBar.isVisibile = false

2023-09-26 13:55 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/CharactersListFragment.kt
> +        binding.progressBar.visibility = View.VISIBLE
binding.progressBar.isVisibile = true

2023-09-26 13:55 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/adapter/CharacterListAdapter.kt
> +    fun updateCharacterList(newCharactersList: List<SingleCharacter>){
перенос строки

2023-09-26 13:55 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/adapter/CharacterListAdapter.kt
> +        notifyDataSetChanged()
хмм, кажется нам тут нужен DiffUtil
у тебя получается каждый раз список обновляется полностью, а это не очень производительно

2023-09-26 13:55 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/utils/interceptors/NetworkException.kt
> +     class ApiException(message: String?) : NetworkException(message)
зачем пробел?)

2023-09-26 15:31 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/MainActivity.kt
>      override fun onCreate(savedInstanceState: Bundle?) {
готово

2023-09-26 15:31 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/MainActivity.kt
> +        setContentView(binding?.root)
я думал, мб пригодится в будущем

2023-09-26 15:32 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/MainActivity.kt
> +        setContentView(binding?.root)
убрал его и вернул всё обратно

2023-09-26 15:34 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/di/module/CharactersViewModelModule.kt
> +        return CharacterListViewModel(
готово

2023-09-26 15:38 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/CharacterListViewModel.kt
> +    private var characters = MutableStateFlow<ViewState<List<SingleCharacter>>>(ViewState.Loading)
готово

2023-09-26 15:38 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/CharactersListFragment.kt
> +        binding.progressBar.visibility = View.GONE
готово

2023-09-26 15:38 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/CharactersListFragment.kt
> +        binding.progressBar.visibility = View.VISIBLE
готово

2023-09-26 15:39 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/adapter/CharacterListAdapter.kt
> +    fun updateCharacterList(newCharactersList: List<SingleCharacter>){
готово

2023-09-26 15:40 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/utils/interceptors/NetworkException.kt
> +     class ApiException(message: String?) : NetworkException(message)
исправил

2023-09-26 16:25 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/MainActivity.kt
> +        setContentView(binding?.root)
вспомнил для чего это пригодится)
я добавлю потом в mainactivity bottomnavigationmenu
тогда в таске, где я его добавлю и перепишу на биндинг

2023-09-27 16:28 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/MainActivity.kt
> +    var appComponent: AppComponent = DaggerAppComponent.factory().create(this)
готово

2023-09-28 11:54 UTC, elza-khamdeeva requested changes

2023-09-28 11:54 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/di/App.kt
> +interface App {
а зачем нам этот интерфейс? можем без него обойтись, я думаю
AppComponent можно предоставить через companion object

2023-09-28 11:54 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/CharactersListFragment.kt
> +    override fun injectDependencies(appComponent: AppComponent) {
перенос строки перед функцией

2023-09-28 11:54 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/base/BaseFragment.kt
> +    abstract fun injectDependencies(appComponent: AppComponent)
отдели члены класса друг от друга переносами строк, пожалуйста)
слитный код сложно читать

2023-09-28 12:13 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/CharactersListFragment.kt
> +    override fun injectDependencies(appComponent: AppComponent) {
готово

2023-09-28 12:16 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/base/BaseFragment.kt
> +    abstract fun injectDependencies(appComponent: AppComponent)
готово

2023-09-29 13:32 UTC, elza-khamdeeva approved these changes

2023-09-29 13:32 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/Application.kt
> +    }
отформатируй класс

2023-09-29 21:55 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/adapter/CharacterListAdapter.kt
> +        notifyDataSetChanged()
готово

2023-09-30 07:45 UTC, merged