Экран со списком персонажей - Фильтрация списка + рефакторинг кода экрана со списком персонажей
sscracker/RickAndMortyApi pull request #6
Opened 2023-10-06 14:55 UTC by sscracker

2023-10-09 12:21 UTC, elza-khamdeeva requested changes

2023-10-09 12:21 UTC, elza-khamdeeva commented on .idea/deploymentTargetDropDown.xml
вот эти файлы не нужно коммитить
на будущее - надо разобраться с gitignore
почитай как его настроить и какие файлы туда заносить)

2023-10-09 12:21 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/MainActivity.kt
> +        when(it.itemId){
отформатируй файл

2023-10-09 12:21 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/MainActivity.kt
> +        when(it.itemId){
вместо it сделай именованный параметр

2023-10-09 12:21 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/data/characters/list/CharactersRepositoryImpl.kt
> +    private val preferences: SharedPreferences = context.getSharedPreferences(
давай для работы с префами создадим отдельный класс
который будет сюда передаваться в конструкторе

2023-10-09 12:21 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/data/characters/list/mapper/CharactersMapper.kt
> +        page.results.forEach { json ->
почему бы тут map не использовать?

2023-10-09 12:21 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/data/characters/list/mapper/CharactersMapper.kt
> +            "Alive" -> CharacterStatus.ALIVE.ordinal
в const

2023-10-09 12:21 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/data/characters/list/mapper/CharactersMapper.kt
> +            "Female" -> CharacterGender.FEMALE.ordinal
в const

эти поля с бэка приходят?

2023-10-09 12:21 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/di/module/characters/CharactersBindsModule.kt
> +    @Singleton
а почему репозиторий Singleton?

2023-10-09 12:21 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/domain/characters/list/usecases/GetCharacterFilterUseCase.kt
> +class GetCharacterFilterUseCase @Inject constructor(
надо закрыть интерфейсом

2023-10-09 12:21 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/domain/characters/list/usecases/GetCharactersUseCase.kt
> +class GetCharactersUseCase @Inject constructor(
тут тоже

2023-10-09 12:21 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/CharacterListViewModel.kt
> +    private var job: Job? = null
помести var под val

2023-10-09 12:21 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/CharacterListViewModel.kt
> +                if (it.isEmpty()) {
замени it на именованные параметры

2023-10-09 12:21 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/CharactersFiltersFragment.kt
> +            3 -> CharacterStatus.UNKNOWN
нужно как-то обозначить позиции

2023-10-09 12:21 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/CharactersListFragment.kt
> +        val args = requireArguments()
вот тут переменная лишняя, обращайся сразу requireArguments

а вообще лучше так

val tabName by lazy { requireArguments().getString(KEY_TAB_NAME) }

2023-10-09 12:21 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/CharactersListFragment.kt
> +                viewModel.emptyResultState.onEach {
поставь переносы строк перед viewModel, сливается а то)

а почему бы не вызвать viewModel. emptyResultState.launch { } ?

или

repeatOnStarted { 
       viewModel. emptyResultState.launch { } 
}

2023-10-09 12:21 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/CharactersListFragment.kt
> +            override fun onQueryTextChange(p0: String?): Boolean {
нужно поправить названия аргументов на смысловые)

2023-10-09 14:45 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/MainActivity.kt
> +        when(it.itemId){
готово

2023-10-10 07:33 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/data/characters/list/mapper/CharactersMapper.kt
> +            "Female" -> CharacterGender.FEMALE.ordinal
Да, эти значения приходят с бэка

2023-10-10 07:46 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/data/characters/list/mapper/CharactersMapper.kt
> +            "Alive" -> CharacterStatus.ALIVE.ordinal
готово

2023-10-10 07:46 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/data/characters/list/mapper/CharactersMapper.kt
> +            "Female" -> CharacterGender.FEMALE.ordinal
готово

2023-10-10 11:23 UTC, sscracker commented on .idea/deploymentTargetDropDown.xml
хорошо

2023-10-10 12:29 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/data/characters/list/CharactersRepositoryImpl.kt
> +    private val preferences: SharedPreferences = context.getSharedPreferences(
готово

2023-10-10 12:29 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/data/characters/list/mapper/CharactersMapper.kt
> +        page.results.forEach { json ->
готово

2023-10-10 12:35 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/di/module/characters/CharactersBindsModule.kt
> +    @Singleton
Решил просто попробовать так сделать)
Вернул как было до этого)

2023-10-10 12:48 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/domain/characters/list/usecases/GetCharacterFilterUseCase.kt
> +class GetCharacterFilterUseCase @Inject constructor(
готово

2023-10-10 12:57 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/domain/characters/list/usecases/GetCharactersUseCase.kt
> +class GetCharactersUseCase @Inject constructor(
готово

2023-10-10 13:14 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/CharacterListViewModel.kt
> +    private var job: Job? = null
job изменяемая переменная

2023-10-10 13:17 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/CharacterListViewModel.kt
> +                if (it.isEmpty()) {
готово

2023-10-10 13:18 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/CharactersFiltersFragment.kt
> +            3 -> CharacterStatus.UNKNOWN
ты имеешь в виду вынести их в константы?

2023-10-10 13:22 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/CharactersListFragment.kt
> +        val args = requireArguments()
готово

2023-10-10 13:38 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/CharactersListFragment.kt
> +                viewModel.emptyResultState.onEach {
А как? У Flow же нет метода launch()

2023-10-10 13:41 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/list/CharactersListFragment.kt
> +            override fun onQueryTextChange(p0: String?): Boolean {
готово

2023-10-11 12:21 UTC, elza-khamdeeva requested changes

2023-10-11 12:21 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/data/characters/list/mapper/CharactersMapper.kt
> +@ActivityScope
перенос строки перед ActivityScope

давай отделять блоки кода для лучшей читаемости, это важно)

2023-10-11 12:21 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/data/characters/list/mapper/CharactersMapper.kt
> +        page.results.map { json ->
не, не так я имела ввиду

fun mapPageToDbModelList(page: ResponseDto) = page.results.mapNotNull {
       Gson().fromJson(json, CharacterDto::class.java)?.let(::mapDtoToDbModel)
}

2023-10-11 12:21 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/utils/Preferences.kt
> +}
отформатируй файл

2023-10-11 12:24 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/data/characters/list/mapper/CharactersMapper.kt
> +@ActivityScope
готово

2023-10-11 12:31 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/data/characters/list/mapper/CharactersMapper.kt
> +        page.results.map { json ->
готово

2023-10-11 12:31 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/utils/Preferences.kt
> +}
готово

2023-10-11 12:57 UTC, elza-khamdeeva approved these changes

2023-10-11 12:58 UTC, merged