Экран со списком персонажей - Детали персонажа
sscracker/RickAndMortyApi pull request #7
Opened 2023-10-12 13:08 UTC by sscracker

https://trello.com/c/QePhK1XU

2023-10-13 13:34 UTC, elza-khamdeeva requested changes

2023-10-13 13:34 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/details/CharacterDetailsFragment.kt
> +    private fun notifyViewModel(){
форматни код)

2023-10-13 13:34 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/details/CharacterDetailsFragment.kt
> +        binding.characterDetailsErrorTextView.visibility = View.VISIBLE
isVisible = true

2023-10-13 13:34 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/details/CharacterDetailsFragment.kt
> +            setOnClickListener(null)
зачем занулять листенер?

2023-10-13 13:34 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/details/CharacterDetailsFragment.kt
> +        binding.characterDetailsProgressBar.visibility = View.VISIBLE
isVisible = true

2023-10-13 13:34 UTC, elza-khamdeeva commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/details/CharacterDetailsFragment.kt
> +        binding.characterDetailsProgressBar.visibility = View.GONE
isVisible = false

2023-10-14 07:07 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/details/CharacterDetailsFragment.kt
> +    private fun notifyViewModel(){
готово

2023-10-14 07:25 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/details/CharacterDetailsFragment.kt
> +            setOnClickListener(null)
исправил

2023-10-14 07:25 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/details/CharacterDetailsFragment.kt
> +        binding.characterDetailsProgressBar.visibility = View.VISIBLE
исправил

2023-10-14 07:25 UTC, sscracker commented on app/src/main/java/ru/example/rickandmortyproject/presentation/characters/details/CharacterDetailsFragment.kt
> +        binding.characterDetailsProgressBar.visibility = View.GONE
исправил

2023-10-16 13:56 UTC, elza-khamdeeva approved these changes

2023-10-16 17:35 UTC, merged